### PR TITLE
Make flaky numeric test JVM-only

### LINKED ISSUE #353: Intermittently failing AstTest?
```
failing seed for AstTest..getDouble is Zy1vv0BOnaXZr52spaBpUaYA9UiYRjBHEt0jCVZ-_fI=
[info] + AstTest..getInt: OK, passed 100 tests.
[info] + AstTest..getBoolean: OK, passed 100 tests.
[info] ! AstTest..getDouble: Falsified after 14 passed tests.
[info] > ARG_0: 11336770021668202000
[info] > ARG_0_ORIGINAL: 181388320346691240000
```

### PR DESCRIPTION
**Pull request by armanbilge**
Fixes #353.

### CODE REVIEW

**Review by rossabaker — DISMISSED** [review]
:+1: if green

**Comment by rossabaker** [comment]
Wait, doesn't it need to move into `AstCheckPlatform`?  (Also, could that file that contains it be renamed?  I had to go on a treasure hunt.)

**Comment by armanbilge** [comment]
Yes, I caught onto it just now too! Forgot to add to the commit, fixed.

Yeah, the file naming is weird, I can fix?

**Comment by rossabaker** [comment]
Yeah, I think your subsequent commit might clash with `ParseCheckPlatform.scala`.

I'm an Old Java Fart who still likes filenames to match the classes they contain, even though scalac is more tolerant.

**Review by rossabaker — APPROVED** [review]
Okay, this looks right.

**Comment by armanbilge** [comment]
I think it's fixed now. And I agree! Just how I found it.

**Pull request merged**
