### PR TITLE
Cross-build for Scala.js

### PR DESCRIPTION
**Pull request by armanbilge**
Cross-building Jawn to Scala.js is a stepping stone towards https://github.com/http4s/http4s/pull/4938

This was almost entirely straightforward. I had to play a bit fast-and-loose with testing, due to different semantics on JS (namely lack of numerical types and much less strict indexing rules).

Thanks in advance!

### CODE REVIEW

**Review by djspiewak — APPROVED** [review]

**Comment by armanbilge** [comment]
@djspiewak thanks for the review! Much appreciated. Mind triggering the CI again please? 😅

**Comment by armanbilge** [comment]
Hope this can be merged/released soon-ish, so I can make a start on the next upstream PR to circe before finding my way back to http4s.

**Comment by travisbrown** [comment]
@armanbilge What's the intention for a Circe PR? Circe already supports cross-platform parsing with circe-parser, which uses Jawn on the JVM and `JSON.parse` for JavaScript, and that's extremely unlikely to change.

**Comment by armanbilge** [comment]
@travisbrown thanks for chiming in. My plan was to cross `circe-jawn` for JS as well so that I can fully cross the `circe` module in http4s. AFAICT the jawn parser supports features like stream decoding etc. that `JSON.parse` does not ... maybe for the browser this is nonsense, but many people seem interested in running http4s client/server on Node.js where I think this could be useful.

I don't think that `circe-parser` should change, but would it hurt to have a cross of `circe-jawn` available on JS for those who wish to use it? Thanks for your thoughts.

**Comment by travisbrown** [comment]
@armanbilge Agreed, circe-fs2 for Scala.js does make sense, and I guess there's no reason not to do circe-jawn as well.

**Comment by armanbilge** [comment]
Excellent!! I appreciate your support. PR forthcoming :)

**Comment by armanbilge** [comment]
@rossabaker do you have a moment to review? Thanks!

**Review by rossabaker — APPROVED** [review]
This is likely to be a bad time for #340, but the approach and implementation look sound.

**Comment by armanbilge** [comment]
I did see that, unfortunate! But #340 seems blocked by other things atm.

Thanks for the review! Now with 2 ✅ , any chance of a merge/release please? 😅

**Comment by rossabaker** [comment]
I'm not on a laptop that can do a release, but I'll see what I can do this week if nobody beats me to it.

**Comment by armanbilge** [comment]
No worries, thank you!! Much much appreciated. Another PR coming your way in `jawn-fs2`.

**Comment by armanbilge** [comment]
@rossabaker thank you very much for releasing! ❤️

**Pull request merged**
