### PR TITLE
Update Scala to 3.0.0

### PR DESCRIPTION
**Pull request by julienrf**
Remove support for 3.0.0-RC2

I’m not sure you want to keep 3.0.0-RC3 as well?

### CODE REVIEW

**Comment by rossabaker** [comment]
Two has been our pattern so people have an upgrade path, but now that 3.0.0 is here, I'd be in favor of letting the RCs go.

**Comment by julienrf** [comment]
I’ve removed RC3 support. May I ask you to run the CI?

**Comment by larsrh** [comment]
Thanks, I'm on it!

**Comment by larsrh** [comment]
scalafmt is failing

**Comment by larsrh** [comment]
Thanks Julien!

**Comment by julienrf** [comment]
Do you plan to publish a release soon?

**Comment by larsrh** [comment]
Already done.

**Pull request merged**
